//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainingInformationSystem.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserTestLesson
    {
        public int IDUserTestLesson { get; set; }
        public int IDUser { get; set; }
        public int IDTestLesson { get; set; }
        public System.DateTime TestDate { get; set; }
    
        public virtual TestLesson TestLesson { get; set; }
        public virtual User User { get; set; }
    }
}
